#!/bin/sh

# Load Husky (new recommended approach)
. "$(dirname "$0")/_/husky.sh"

# Define files or directories to exclude from pre-commit checks
excluded_files="package-lock.json|README.md|client/|server/|.husky/pre-commit|package.json"

# Get a list of staged files, excluding specified patterns
fileList=$(git diff --staged --name-only | grep -v -E "$excluded_files")

echo '----- Checking Root...'

if [ ! -z "$fileList" ]; then
  echo "error: Unauthorized modifications\n"
  echo "$fileList\n"
  echo "use 'git restore --staged ...' to fix the problem"
  echo "(and ask your instructor why you should not change these files)\n"
  exit 1
fi

# Additional validations
npx validate-branch-name
npm run lint

echo '----- Done!'





